-- Event/attribute taxonomy. Names follow Gramps; gedcom_tag follows GEDCOM 7.
INSERT INTO event_type (name, kind, gedcom_tag, gramps_name) VALUES
 ('Birth','event','BIRT','Birth'),
 ('Death','event','DEAT','Death'),
 ('Burial','event','BURI','Burial'),
 ('Cremation','event','CREM','Cremation'),
 ('Baptism','event','BAPM','Baptism'),
 ('Christening','event','CHR','Christening'),
 ('Adult Christening','event','CHRA','Adult Christening'),
 ('Adopted','event','ADOP','Adopted'),
 ('Bar Mitzvah','event','BARM','Bar Mitzvah'),
 ('Bas Mitzvah','event','BASM','Bas Mitzvah'),
 ('Blessing','event','BLES','Blessing'),
 ('Confirmation','event','CONF','Confirmation'),
 ('First Communion','event','FCOM','First Communion'),
 ('Ordination','event','ORDN','Ordination'),
 ('Census','event','CENS','Census'),
 ('Residence','event','RESI','Residence'),
 ('Emigration','event','EMIG','Emigration'),
 ('Immigration','event','IMMI','Immigration'),
 ('Naturalization','event','NATU','Naturalization'),
 ('Arrival','event','EVEN','Arrival'),
 ('Departure','event','EVEN','Departure'),
 ('Graduation','event','GRAD','Graduation'),
 ('Education','event','EDUC','Education'),
 ('Degree','event','EVEN','Degree'),
 ('Occupation','attribute','OCCU','Occupation'),
 ('Retirement','event','RETI','Retirement'),
 ('Military Service','event','EVEN','Military Service'),
 ('Military Draft','event','EVEN','Military Draft'),
 ('Probate','event','PROB','Probate'),
 ('Will','event','WILL','Will'),
 ('Property','event','PROP','Property'),
 ('Land Grant','event','EVEN','Land Grant'),
 ('Tax','event','EVEN','Tax'),
 ('Voter Registration','event','EVEN','Voter Registration'),
 ('Religion','attribute','RELI','Religion'),
 ('Nobility Title','attribute','TITL','Nobility Title'),
 ('Elected','event','EVEN','Elected'),
 ('Medical Information','attribute','EVEN','Medical Information'),
 ('Cause of Death','attribute','CAUS','Cause Of Death'),
 ('Marriage','family_event','MARR','Marriage'),
 ('Marriage License','family_event','MARL','Marriage License'),
 ('Marriage Banns','family_event','MARB','Marriage Banns'),
 ('Marriage Contract','family_event','MARC','Marriage Contract'),
 ('Marriage Settlement','family_event','MARS','Marriage Settlement'),
 ('Engagement','family_event','ENGA','Engagement'),
 ('Divorce','family_event','DIV','Divorce'),
 ('Divorce Filing','family_event','DIVF','Divorce Filing'),
 ('Annulment','family_event','ANUL','Annulment'),
 ('Alternate Marriage','family_event','MARR','Alternate Marriage'),
 ('Number of Marriages','attribute','NMR','Number of Marriages'),
 -- persona-level attributes that are not Gramps events
 ('Name','attribute','NAME',NULL),
 ('Sex','attribute','SEX',NULL),
 ('Age','attribute','AGE',NULL),
 ('Relationship','attribute',NULL,NULL),
 ('Marital Status','attribute','FACT',NULL),
 ('Nationality','attribute','NATI','Nationality'),
 ('Race','attribute','FACT',NULL),
 ('Physical Description','attribute','DSCR','Description'),
 ('Literacy','attribute','FACT',NULL),
 ('Social Security Number','attribute','SSN','Social Security Number'),
 ('Identification Number','attribute','IDNO','Identification Number'),
 ('Inscription','attribute','FACT',NULL),
 ('Unknown','event','EVEN','Unknown');
